services:
  - type: web
    name: Aduhub-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    runtime: python
    pythonVersion: 3.10.13
    
