services:
  - type: web
    name: telegram-ad-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    runtime: python
    pythonVersion: 3.12.0

